### ISSUE TITLE
IndexError because pytorch does not support int32 for indexing like onnx

### ISSUE THREAD

**Issue by samedii** [ENOT-AutoDL/onnx2torch#106]
Been trying a bunch of things to solve this now but the error message isn't very helpful. It just sounds like it's just the input dtype that's handled incorrectly.

```
  File "/home/richard/miniconda3/envs/3.9.13/lib/python3.9/site-packages/torch/fx/graph_module.py", line 630, in wrapped_call
    raise e.with_traceback(None)
IndexError: tensors used as indices must be long, byte or bool tensors
```

Here is the onnx file I'm trying to convert
https://drive.google.com/file/d/1FX_D6dcYEoVssr-y29F5RLbhmhf4RmyZ/view?usp=sharing

It is supposed to take a tensor of type long. Here's an example in json:
https://drive.google.com/file/d/1yTSxwOY10g0cULEVt3KQZWSzziDpD8bC/view?usp=sharing

This is how I try to run it:
```
    model = torch.load(torch_path).eval().requires_grad_(False)

    tokens = torch.tensor(
        json.loads(Path(f"tests/{model_name}/tokens.json").read_text())
    ).long()
    text_encodings = torch.from_numpy(np.array(model(tokens)))
```

_The onnx file works with onnxruntime and gives the correct result._
```
    tokens = np.array(
        json.loads(Path(f"tests/{model_name}/tokens.json").read_text())
    ).astype(np.int64)

    providers = ["CPUExecutionProvider"]
    m = rt.InferenceSession(onnx_path, providers=providers)
    text_encoding = m.run(output_names, dict(inputs=tokens))
```

Do you have any tips for what could be wrong?

**Comment by samedii** [comment]
After some more debugging I think that that since the model is converted from JAX it's using int32 when slicing embeddings rather than long/int64. That works fine with onnx but isn't supported in pytorch

I tried converting explicitly to int64 inside the model and using `jax.config.update("jax_enable_x64", True)` when exporting but it didn't help

**Comment by samedii** [comment]
A similar issue also seems to happen when trying to use the model in onnxjs where it does not support int64 and they need to convert to int32. They insert cast operations into the graph to solve this type of issue here
https://github.com/microsoft/onnxruntime/blob/c6732c079b4fbf644bc939729c87d70195251d83/onnxruntime/python/tools/transformers/onnx_model_bert.py#L125-L202

Been trying to modify my onnx to replicate this for a while.

**Comment by senysenyseny16** [comment]
Hello, samedii.

We will look into the issue and try to come up with a solution next week.

**Comment by samedii** [comment]
@senysenyseny16 Thank you! I had to give up eventually on fixing the ONNX file manually. At the moment I'm running the text encoder via ONNX because it's not used as often as the image encoder (text-guided image generation) but it would be very nice if it wasn't necessary.

The package is open source if you want to know what it would be used for: https://github.com/samedii/pytorch-zero-lit

**Comment by samedii** [comment]
Ping

**Comment by senysenyseny16** [comment]
Hi @samedii 

Sorry for the wait, we will get back to this issue as soon as possible.

**Comment by samedii** [comment]
Just showing there's still interest 🙂

**Comment by senysenyseny16** [comment]
Hi @samedii, fix in main branch.

**Comment by samedii** [comment]
Thank you! 🙏
