### ISSUE TITLE
GatherND missing 

### ISSUE THREAD

**Issue by jonas-doevenspeck** [ENOT-AutoDL/onnx2torch#107]
While mentioned in release v1.2.0, GatherND is not implemented.
See https://github.com/ENOT-AutoDL/onnx2torch/pull/25.
Are there any plans to still add the operator?

**Comment by senysenyseny16** [comment]
Hello, @jonas-doevenspeck.

> While mentioned in release v1.2.0, GatherND is not implemented.
Yes, this our mistake.

> Are there any plans to still add the operator?
Yes, but it might not be trivial for general case.
Which case are you interested in? In terms of data and indices shape and batch_dims?

**Comment by senysenyseny16** [comment]
#122
