### ISSUE TITLE
Is There any possible way to have OnnxGemm converted into torch.nn.Linear?

### ISSUE THREAD

**Issue by feanor21115** [ENOT-AutoDL/onnx2torch#108]
Hi, It is kind of you to share your work.
Very appreciate it.

I have noticed that the GEMM layer of the onnx graph will be converted into a object of OnnxGemm.

for example:
![image](https://user-images.githubusercontent.com/12491617/196866600-38893d27-6c46-4e35-94a1-43d6518a67fe.png)

then we check the pytorch model
![image](https://user-images.githubusercontent.com/12491617/196866752-8887c13e-6d85-462b-8412-e9f4be158491.png)
and its forward
![image](https://user-images.githubusercontent.com/12491617/196866997-f5ca6489-952e-4118-8094-cc3f2e168005.png)

I wonder that is it possible to have these GEMMs converted into PyTorch native module?
And it will be much more scalable.

Thank you!!

**Comment by senysenyseny16** [comment]
Hello, @feanor21115 

We do this [if possible](https://github.com/ENOT-AutoDL/onnx2torch/blob/main/onnx2torch/node_converters/gemm.py#L60) - all inputs except the first one are initializers.

**Comment by feanor21115** [comment]
Thank you!!!
