### ISSUE TITLE
Gemm Bug

### ISSUE THREAD

**Issue by JiangYongYu1** [ENOT-AutoDL/onnx2torch#109]
https://github.com/ENOT-AutoDL/onnx2torch/blob/2791442c88af2bd243d0092963838ce940f8f1b0/onnx2torch/node_converters/gemm.py#L67
is wrong, it should be `if bias is None or bias.dim() == 1:`

**Comment by senysenyseny16** [comment]
fixed: https://github.com/ENOT-AutoDL/onnx2torch/commit/0fc83d173bf80d8886b91c657abdcc32ad4e0e46
