### ISSUE TITLE
save converted yolov5

### ISSUE THREAD

**Issue by clh-b** [ENOT-AutoDL/onnx2torch#110]
Exported the module to folder using "to_folder" and encounter "NameError: name 'onnx2torch_converter_lambda_' is not defined" error when inference after import the module. Any tips what's wrong?

**Comment by senysenyseny16** [comment]
Hello, @clh-b.

Could you provide minimal example to reproduce this error?

**Comment by senysenyseny16** [comment]
I hope #118 solves your problem.

Feel free to reopen PR.

**Comment by clh-b** [comment]
> Hello, @clh-b.
> 
> Could you provide minimal example to reproduce this error?

Tested v1.5.6, the error is solved. Thanks
