### ISSUE TITLE
KeyError: 'Tensor "onnx::Clip_2052" is not found in constant values'

### ISSUE THREAD

**Issue by NeoKun004** [ENOT-AutoDL/onnx2torch#115]
Trying to convert a LayoutMl model to pytorch model getting this error : 

KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/onnx2torch/node_converters/clip.py](https://localhost:8080/#) in _(node, graph)
     56     try:
---> 57         min_val = float(get_const_value(min_name, graph)) if min_name is not None else None
     58         max_val = float(get_const_value(max_name, graph)) if max_name is not None else None

3 frames
KeyError: 'Tensor "onnx::Clip_2052" is not found in constant values'

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/onnx2torch/node_converters/clip.py](https://localhost:8080/#) in _(node, graph)
     58         max_val = float(get_const_value(max_name, graph)) if max_name is not None else None
     59     except KeyError as exc:
---> 60         raise NotImplementedError('Dynamic value of min/max is not implemented') from exc
     61 
     62     torch_module = _create_torch_module(min_val=min_val, max_val=max_val)

NotImplementedError: Dynamic value of min/max is not implemented

**Comment by senysenyseny16** [comment]
Hello, @NeoKun004.

Could you provide ONNX to reproduce your issue?
