### ISSUE TITLE
adding QuantizeLinear and DequantizeLinear to the project #123

### ISSUE THREAD

**Issue by Soyuz0** [ENOT-AutoDL/onnx2torch#124]
hello
I'm trying to a add a QuantizeLinear and DequantizeLinear layers and I just want someone to take a look because I'm having issues with them in my own project:

[Archive 2.zip](https://github.com/ENOT-AutoDL/onnx2torch/files/10474235/Archive.2.zip)

**Comment by senysenyseny16** [comment]
Hello, @Soyuz0.

Were you able to implement QLinear-DQLinear?

**Comment by Soyuz0** [comment]
> Hello, @Soyuz0.
> 
> 
> 
> Were you able to implement QLinear-DQLinear? 

Hi
Not really but I did implement something that works for me in some specific case
If you could implement one generally that would be great

You also need to update the conv operator since it can take the output of a DQ-leaner layer as a weight/ bias
