### ISSUE TITLE
support for layernorm

### ISSUE THREAD

**Issue by jonas-doevenspeck** [ENOT-AutoDL/onnx2torch#126]
Are there any plans to support LayerNorm?
It's available in onnx-opset 17 which can be exported to from torch>=1.13
It's commonly used in transformers so would be very useful!

**Comment by senysenyseny16** [comment]
Hello, @jonas-doevenspeck 

Since PyTorch has [LayerNorm](https://pytorch.org/docs/stable/generated/torch.nn.LayerNorm.html) module this shouldn't be hard.

I think we will add support soon.

**Comment by JohnMasoner** [comment]
#143

**Comment by senysenyseny16** [comment]
up

**Comment by upskyy** [comment]
@senysenyseny16 I am also trying to convert a model with onnx-opset 17 to a torch. Is LayerNorm supported?
Do you have any updates?

**Comment by senysenyseny16** [comment]
hi @upskyy updated PR: #165, i think it will be merged in coming days.

**Comment by senysenyseny16** [comment]
@JohnMasoner @jonas-doevenspeck @upskyy 

released: https://github.com/ENOT-AutoDL/onnx2torch/releases/tag/v1.5.9

**Comment by senysenyseny16** [comment]
Feel free to reopen if there are any problems or questions.
