### ISSUE TITLE
Wrong shape from average pool

### ISSUE THREAD

**Issue by JohnMasoner** [ENOT-AutoDL/onnx2torch#133]
I've recently been trying to convert models on [MONAI](https://github.com/project-MONAI/MONAI/) to onnx and then to torch. i'm having some problems getting wrong shapes when i set the deconv method to pixelshuffle.

Here is my code to better implement this.

```shell
❯ pip list | grep torch
onnx2torch                         1.5.4
pytorch-ignite                     0.4.9
torch                              1.12.1+cu116
torchaudio                         0.7.0a0+a853dff
torchfile                          0.1.0
torchio                            0.18.71
torchsummary                       1.5.1
torchvision                        0.8.2
```
```shell
❯ pip list | grep monai
monai                              1.1.0
```

```shell
❯ pip list | grep onnx
onnx                               1.13.0
onnx2torch                         1.5.4
onnxruntime                        1.13.1
```

script:
```python
import onnx2torch
import torch
from monai.networks.nets import BasicUNetPlusPlus

model1 = BasicUNetPlusPlus(2, upsample = 'pixelshuffle')

batch_size = 1
x = torch.randn(batch_size, 1, 512, 512, requires_grad=True)
torch_out = model1(x)

# Export the model
torch.onnx.export(model1,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "model.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True)

file = 'model.onnx'
model = onnx2torch.convert(file)

print(model)
```

I get the following error:
```python
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.7/site-packages/onnx2torch/node_converters/average_pool.py", line 30, in _
    avgpool_class = _AVGPOOL_CLASS_FROM_SPATIAL_RANK[spatial_rank]
KeyError: -2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "torch2.py", line 18, in <module>
    model = onnx2torch.convert(file)
  File "/home/xxx/.local/lib/python3.7/site-packages/onnx2torch/converter.py", line 109, in convert
    torch_module, onnx_mapping = converter(onnx_node, onnx_graph)
  File "/home/xxx/.local/lib/python3.7/site-packages/onnx2torch/node_converters/average_pool.py", line 34, in _
    ) from exc
NotImplementedError: Average pool operation with spatial rank == -2 is not implemented
```

I print the code
```python
def _(node: OnnxNode, graph: OnnxGraph) -> OperationConverterResult:
    input_value_info = graph.value_info[node.input_values[0]]
    input_shape = get_shape_from_value_info(input_value_info)
    print(input_shape)
```
the input shape is `[0,0,0,0]`

**Comment by JohnMasoner** [comment]
I temporarily set spatial rank to 2 and solved my problem. But this is obviously a temporary solution and I am looking for options to solve it.

**Comment by JohnMasoner** [comment]
I've just looked at #121  and this seems to be the same issue.

**Comment by senysenyseny16** [comment]
Hi @JohnMasoner 

Could you check conversion with `onnx2torch==1.5.6`?

**Comment by senysenyseny16** [comment]
I was able to reproduce it, the problem is in the PyTorch tracing mechanism.
The fastest and simplest solution is to update your PyTorch to 1.13.x (if it possible for you).

**Comment by JohnMasoner** [comment]
> I was able to reproduce it, the problem is in the PyTorch tracing mechanism. The fastest and simplest solution is to update your PyTorch to 1.13.x (if it possible for you).

Many Thnaks @senysenyseny16,

I updated the PyTorch to 1.13.1 to solve this problem.

**Comment by senysenyseny16** [comment]
Also, I think the torch.export in PyTorch 1.12.x slightly breaks the model:

```bash
❯ python3 /venv39/lib/python3.9/site-packages/onnxruntime/tools/symbolic_shape_infer.py --input monai_1_12.onnx --output monai_1_12_infer.onnx
Traceback (most recent call last):
  File ".../symbolic_shape_infer.py", line 2411, in <module>
    out_mp = SymbolicShapeInference.infer_shapes(
  File ".../symbolic_shape_infer.py", line 2347, in infer_shapes
    raise Exception("Incomplete symbolic shape inference")
Exception: Incomplete symbolic shape inference
```

On PyTorch 1.13.x shape inference works as expected.

**Comment by tan-may16** [comment]
Hello, I am facing a similar issue. But following the above discussion is not working. This is the error I am getting:
NotImplementedError: BatchNorm operation with spatial rank == -2 is not implemented

please let me know what could be done to resolve the issue. Thank you.

**Comment by RainFrost1** [comment]
> Hello, I am facing a similar issue. But following the above discussion is not working. This is the error I am getting: NotImplementedError: BatchNorm operation with spatial rank == -2 is not implemented
> 
> please let me know what could be done to resolve the issue. Thank you.

Have you find  a solution?
