### ISSUE TITLE
OnnxResize and our pruning strategy

### ISSUE THREAD

**Issue by agoncharenko1992** [ENOT-AutoDL/onnx2torch#24]
Our pruning strategy does not work when applied to the OnnxResize module due to the fact that the input shapes have changed, and the sizes that come to forward have not changed (if they are constant). It is necessary to remove the check during the inference and do the check during the creation of this module.

**Comment by ivkalgin** [comment]
https://github.com/ENOT-AutoDL/onnx2torch/pull/67
