### ISSUE TITLE
error: import fx from torch

### ISSUE THREAD

**Issue by lzu-zhanghr** [ENOT-AutoDL/onnx2torch#29]
when import torch.fx  in converter.py line 10

attributeError: module 'torch' has no attribute '_assert'

torch:1.8

**Comment by lzu-zhanghr** [comment]
fix this bug: import torch._fx as fx

**Comment by irkjero** [comment]
Hello!
Please send us list of installed packages (pip list) and information about your operation system and hardware.
Also please provide a piece of code to reproduce the issue.

Thank you!

**Comment by senysenyseny16** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one if you have further questions.
