### ISSUE TITLE
Only Symmetric Padding Supported

### ISSUE THREAD

**Issue by geoeo** [ENOT-AutoDL/onnx2torch#52]
Hello,

I converted a frozen tf network (pb) to onnx via tf2onnx. 
Now I am trying to convert it to pytorch via this library. 
However I get the following error:

```
    raise NotImplementedError(f'Only symmetric padding is implemented ({padding})')
NotImplementedError: Only symmetric padding is implemented ([1, 1, 0, 0])
```

Is this something I can fix? Is is fixable in general?

Best

**Comment by niobeus** [comment]
Hello,
It looks like you are using padding which is not supported in Pytorch. To solve this problem, try splitting your conv operation into two operation: padding and conv with valid mode.

**Comment by geoeo** [comment]
Thanks . I guess this is on your responsibility
