### ISSUE TITLE
PRelu Support 

### ISSUE THREAD

**Issue by xxoospring** [ENOT-AutoDL/onnx2torch#58]
Does the latest version support PRelu ?

**Comment by irkjero** [comment]
Hello! Thank you for your question.
Latest version doesn't support 'PRelu'.
Here you can find a list currently supported operations: https://github.com/ENOT-AutoDL/onnx2torch/blob/main/operators.md

**Comment by zhiqwang** [comment]
Hi @irkjero , I've met the save question here, is there a plan to support `PRelu` in torch2onnx?

**Comment by zhiqwang** [comment]
Hi @senysenyseny16 and @irkjero , I write a quick implementation for PRelu operator in #71, hope this can help to close this issue.

**Comment by irkjero** [comment]
Thank you. Your pull request has been approved.
