### ISSUE TITLE
Does not support the convert of xception?

### ISSUE THREAD

**Issue by koon-kai** [ENOT-AutoDL/onnx2torch#85]
I successfully converted the Xception ONNX model file to a .pt file, but the predicted data is inconsistent with the original ONNX file.

Is there any unsupported operation?  but also did not throw any error message when converting.

**Comment by ivkalgin** [comment]
Hello @koon-kai,
Please, give me the link to your onnx. What version of onnx2torch and version of pytorch do you use?

**Comment by niobeus** [comment]
Hello @koon-kai,
Xception from timm works well. Can your give us the link to your onnx file?

**Comment by koon-kai** [comment]
@niobeus @ivkalgin 

I checked the weight of the pt file after the conversion, it is the same as the original one, the inconsistency should have nothing to do with the conversion tool.

I will close this issue.

Thank you both.
