### ISSUE TITLE
release on conda-forge or similar?

### ISSUE THREAD

**Issue by monicathieu** [ENOT-AutoDL/onnx2torch#87]
Hi there,

Are there plans to release the package for conda installation through conda-forge or another channel? I would love to be able to conda install this package so it will track in my conda environments.

(My personal machine is on Mac OS, and I also work on a Linux server, so if I could put in requests for build OSs it would be those.)

thank you for your consideration!

**Comment by senysenyseny16** [comment]
hi Monica,

conda should track packages installed from PyPI (by `pip`), could you provide steps to reproduce your issue?

```bash
>>> conda activate ...
>>> pip install onnx2torch

>>> pip list | grep onnx2torch
onnx2torch              1.4.1

>>> conda list | grep onnx2torch
onnx2torch                1.4.1                    pypi_0    pypi
```

**Comment by monicathieu** [comment]
Hi, yes! onnx2torch does appear as being sourced from PyPI when I `conda list`.

```bash
conda list | grep onnx2torch
onnx2torch                1.4.1                    pypi_0    pypi
```

I should have been a bit more specific--are there plans to release the package on a channel like conda-forge such that this works to install as well?

```bash
conda install -c conda-forge onnx2torch
```

Where possible, I've been trying to only use the conda-install-able versions of packages so that I don't [accidentally overwrite a dependency](https://www.anaconda.com/blog/using-pip-in-a-conda-environment) for a pip-installed package by conda installing something else later. I'm just starting a new project so I definitely haven't yet discovered or installed all the packages I might need by this point!

**Comment by senysenyseny16** [comment]
> Where possible, I've been trying to only use the conda-install-able versions of packages so that I don't [accidentally overwrite a dependency](https://www.anaconda.com/blog/using-pip-in-a-conda-environment) for a pip-installed package by conda installing something else later. I'm just starting a new project so I definitely haven't yet discovered or installed all the packages I might need by this point!

got it, I think we can release onnx2torch to conda-forge on the next week.

**Comment by senysenyseny16** [comment]
Monica,

we submitted PR for conda-forge: https://github.com/conda-forge/staged-recipes/pull/20266, as soon as it is accepted you can install onnx2torch by using `conda install -c conda-forge onnx2torch` command.

Feel free to open new issues and good luck in your research.

**Comment by monicathieu** [comment]
confirmed that it installed from the conda-forge channel! thank you again!
